### ISSUE TITLE
feature: pin to a specific release

### ISSUE THREAD

**Issue by cainlevy** [FedericoCarboni/setup-ffmpeg#16]
Currently this action will install the latest available FFmpeg release. This makes it likely that the version we rely on for testing will be out of sync with our local development and remote production versions.

An option to specify the version would be very helpful.

This option might make some people think they can specify any arbitrary version of ffmpeg and it will be installed. Documentation may be necessary to clarify that only versions tagged in https://github.com/FedericoCarboni/setup-ffmpeg/releases can be chosen.

**Comment by FedericoCarboni** [comment]
It's unfortunate upstream developers that provide the builds decided to change configuration without notice (#15). However I don't really see this as a solution for your specific issue because it will just delay the problem. Eventually ffmpeg 6 will get stale and you will need to find another build that includes the features you need. So I recommend you find a way to get builds with the configuration you need.
That said I understand many projects require more flexibility so I will implement it anyway when I have time, or if you have a fix already you are welcome to make a PR.

**Comment by FedericoCarboni** [comment]
I worked on v3 over the past few days, it's in its own branch v3-preview. It may already be tested. It should be fairly close to being complete but I'm not releasing it just yet.

**Comment by cainlevy** [comment]
Thank you! Looks like a nice improvement. 🎉
